[matugen]

# Main Spotify surfaces
main               = {{ colors.background.default.hex_stripped }}
main-secondary     = {{ colors.surface_container.default.hex_stripped }}

# Accent colors
accent             = {{ colors.primary.default.hex_stripped }}
button             = {{ colors.primary.default.hex_stripped }}
button-secondary   = {{ colors.secondary.default.hex_stripped }}
button-active      = {{ colors.primary_container.default.hex_stripped }}
button-disabled    = {{ colors.surface_container_high.default.hex_stripped }}

# Secondary accent
misc               = {{ colors.tertiary.default.hex_stripped }}

# Text
subtext            = {{ colors.on_surface_variant.default.hex_stripped }}
text               = {{ colors.on_background.default.hex_stripped }}

# Spotify layout surfaces
sidebar            = {{ colors.surface_container_low.default.hex_stripped }}
player             = {{ colors.surface_container.default.hex_stripped }}
card               = {{ colors.surface_container_high.default.hex_stripped }}
notification       = {{ colors.surface_container.default.hex_stripped }}

# Errors
notification-error = {{ colors.error.default.hex_stripped }}

# Misc
shadow             = {{ colors.shadow.default.hex_stripped }}

# Navigation
nav-active-text    = {{ colors.on_primary.default.hex_stripped }}
nav-active         = {{ colors.primary.default.hex_stripped }}

# Tabs
tab-active         = {{ colors.primary_container.default.hex_stripped }}

# Playback
play-button        = {{ colors.primary.default.hex_stripped }}
playback-bar       = {{ colors.primary.default.hex_stripped }}
