# wallust v3.5
backend = "fastresize"
color_space = "salience"
palette = "saliencedark"

[templates]
hyprland = { template = 'hyprland-colors.j2', target = '~/.config/hypr/conf/colors.lua' }
waybar = { template = 'waybar-colors.j2', target = '~/.config/waybar/colors.css' }
rofi = { template = 'rofi-colors.j2', target = '~/.config/rofi/colors.rasi' }
dunst = { template = 'dunst-colors.j2', target = '~/.config/dunst/dunstrc.d/01-wallust.conf' }
keyboard = { template = 'keyboard-color.j2', target = '~/.config/scripts/keyboard-color.txt' }
