# wallust v3.5
backend = "fastresize"
color_space = "salience"
palette = "saliencedark"

[templates]
hyprland = { template = 'hyprland-colors.j2', target = '~/.config/hypr/conf/colors.lua' }
waybar = { template = 'waybar-colors.j2', target = '~/.config/waybar/colors.css' }
rofi = { template = 'rofi-colors.j2', target = '~/.config/rofi/colors.rasi' }
dunst = { template = 'dunst-colors.j2', target = '~/.config/dunst/dunstrc.d/01-wallust.conf' }
keyboard = { template = 'keyboard-color.j2', target = '~/.config/scripts/keyboard-color.txt' }
cava = { template = 'cava-colors.j2', target = '~/.config/cava/themes/wallust' }
wezterm = { template = 'wezterm-colors.j2', target = '~/.config/wezterm/colors/wallust.toml' }
wiremix = { template = 'wiremix.j2', target = '~/.config/wiremix/wiremix.toml' }
gtk3 = { template = 'gtk-colors.j2', target = '~/.config/gtk-3.0/colors.css' }
gtk4 = { template = 'gtk-colors.j2', target = '~/.config/gtk-4.0/colors.css' }
kde = { template = 'kde-colors.j2', target = '~/.local/share/color-schemes/Wallust.colors' }
spotifast = { template = 'spotifast.j2', target = '~/.config/fastpotify/themes/wallust.json' }
