hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("~/.config/ml4w-hyprland-settings/hyprctl.sh")
    hl.exec_cmd("eww daemon")
    hl.exec_cmd("eww open clock")
    hl.exec_cmd("hyprctl eval 'layerrule = \"blur, eww-clock\"'")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("~/.config/ml4w-hyprland-settings/hyprctl.sh")
end)
