# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# NOTE: For floating vesktop
windowrulev2 = float, class:^(vesktop)$
windowrulev2 = size 1600 1000, class:^(vesktop)$
windowrulev2 = center, class:^(vesktop)$
windowrulev2 = workspace special:discord, class:^(vesktop)$
# NOTE: For Obsidian floating
# windowrulev2 = float, class:^(obsidian)$
# windowrulev2 = size 1400 900, class:^(obsidian)$
# windowrulev2 = center, class:^(obsidian)$
# windowrulev2 = workspace special:notes, class:^(obsidian)$
