# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# NOTE: For floating vesktop
# windowrulev2 = float, class:^(vesktop)$
# windowrulev2 = size 1600 1000, class:^(vesktop)$
# windowrulev2 = center, class:^(vesktop)$
# windowrulev2 = workspace special:discord, class:^(vesktop)$
# NOTE: For Obsidian floating
# windowrulev2 = float, class:^(obsidian)$
# windowrulev2 = size 1400 900, class:^(obsidian)$
# windowrulev2 = center, class:^(obsidian)$
# windowrulev2 = workspace special:notes, class:^(obsidian)$
# IMPORTANT: For spotify Floating
# Spotify floating window rule
# windowrulev2 = float, initialClass:^([sS]potify)$
# windowrulev2 = size 1200 800, initialClass:^([sS]potify)$
# windowrulev2 = center, initialClass:^([sS]potify)$ # Optional: center the window
windowrulev2 = float, class:^(com.saivert.pwvucontrol)$
windowrulev2 = size 1200 800, class:^(com.saivert.pwvucontrol)$
windowrulev2 = center, class:^(com.saivert.pwvucontrol)$ # Optional: center the window
